Fixed syntax issue in example.
I believe that this syntax was valid in previous versions of Terraform, but is no longer considered valid.

This will throw the following error as is:

```
Error: Error parsing <DIRECTORY>/ec2.tf: At 3:21: Unknown token: 3:21 IDENT var.image_id
```