builtin/providers/cloudstack: make build pass
'make test' failed due to build failure in cloudstack provider:

# github.com/hashicorp/terraform/builtin/providers/cloudstack
builtin/providers/cloudstack/resource_cloudstack_disk.go:186: too many arguments in call to cs.Volume.NewResizeVolumeParams
builtin/providers/cloudstack/resource_cloudstack_vpc.go:127: not enough arguments in call to cs.VPC.NewUpdateVPCParams
FAIL github.com/hashicorp/terraform/builtin/bins/provider-cloudstack [build failed]

Fix the reported errors to make the build pass.